name: Python CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Крок для клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Встановлюємо Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Встановлюємо залежності
      - name: Install dependencies
        run: |
          pip install pytest coverage

      # Запуск тестів
      - name: Run tests
        run: |
          pytest example/coverage_io/test.py -v

      # Генерація звіту покриття
      - name: Generate Report
        run: |
          cd example/coverage_io/
          coverage run -m unittest -v
          coverage xml

      # Відправка результатів в Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: example/coverage_io/


