name: Python CI Workflow

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # встановлюємо Python пакети
      - name: Install dependencies
        run: |
          pip install pytest coverage

      # запускаємо тести
      - name: Run tests
        run: |
          cd example/coverage_io/
          pytest test.py -v

      # генеруємо звіт
      - name: Generate Report
        run: |
          cd example/coverage_io/
          coverage run -m unittest -v
          coverage xml

      # надсилаємо звіт в Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: example/coverage_io/
