name: actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pytest coverage

    - name: Run tests
      run: |
        cd chapter_2/lab_2
        pytest -v

    - name: Generate Report
      run: |
        cd chapter_2/lab_2
        coverage run -m unittest discover -v
        coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: chapter_2/lab_2
